version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/docker-init"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/android"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/cmake"
    schedule:
      interval: "daily"
