name: Docker Init
description: Common operations for build and push flows

inputs:
  operation:
    description: Operation to perform
    required: true
  dockerhub_username:
    description: Docker Hub username
    required: false
  dockerhub_token:
    description: Docker Hub token
    required: false
  repository_owner:
    description: GitHub repository owner
    required: false
  image_tag:
    description: Docker image tag name
    required: false

outputs:
  tags:
    description: Docker tags
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: Docker labels
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    # Docker Login
    - name: Log into registry
      if: inputs.operation == 'login' && github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/pull') && github.actor != 'dependabot[bot]'
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: docker.io
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    # Extract metadata (tags, labels) for Docker builds
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      if: inputs.operation == 'metadata'
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: docker.io/${{ inputs.repository_owner }}/ninja_${{ inputs.image_tag }}
        tags: |
          type=raw,value=latest,enable=true

